### ISSUE TITLE
x-nucleo-idw01m1 is not able to close socket if server is sending.

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/wifi-x-nucleo-idw01m1#11]
I have a test that downloads 100 kB of known test pattern from [RFC 864](https://tools.ietf.org/html/rfc864) test server through TCP stream.
Looks like this driver is not able to close the socket, if server keeps sending the data.

Board: NUCLEO_F401RE (I believe this is not relevant)
Shield: IDW01M1
Compiler: GCC_ARM

## Steps to reproduce

```
mbed new x-nucleo-test
cd x-nucleo-test
mbed add wifi-x-nucleo-idw01m1
mbed target NUCLEO_F401RE
mbed toolchain GCC_ARM
```

Create `main.cpp`

```
#include "mbed.h"

#include "SpwfSAInterface.h"
SpwfSAInterface wifi(D8, D2);

static void generate_RFC_864_pattern(size_t offset, uint8_t *buf,  size_t len)
{
    while (len--) {
        if (offset % 74 == 72)
            *buf++ = '\r';
        else if (offset % 74 == 73)
            *buf++ = '\n';
        else
            *buf++ = ' ' + (offset%74 + offset/74) % 95 ;
        offset++;
    }
}

static bool check_RFC_864_pattern(void *buffer, size_t len, size_t offset)
{
    void *buf = malloc(len);
    if (!buf)
        return false;
    generate_RFC_864_pattern(offset, (uint8_t*)buf, len);
    bool match = memcmp(buf, buffer, len) == 0;
    if (!match) {
        printf("Pattern check failed\r\nWAS:%.*s\r\nREF:%.*s\r\n", len, (char*)buffer, len, (char*)buf);
    }
    free(buf);
    return match;
}

int main()
{
    printf("Connecting...\n");

    int ret = wifi.connect("SSID", "PASSWORD", NSAPI_SECURITY_WPA_WPA2);
    if (ret != 0) {
        printf("Failed to connect!\n");
        return 0;
    }
    printf("Connected to WiFi\n");

    TCPSocket socket(&wifi);

    ret = socket.connect("echo.mbedcloudtesting.com", 19);
    if (ret) {
        printf("Failed to connect to echo.mbedcloudtesting.com:19\n");
        return 0;
    }

    printf("Connected!\nReceiving 100kB\n");

    uint8_t buf[100];
    for (int received=0; received <= 100000;) {
        ret = socket.recv(buf, 100);
        if (ret <= 0) {
            printf("Error socket.recv returned %d\n", ret);
            return 0;
        }

        if (!check_RFC_864_pattern(buf, ret, received))
            return 0;

        received += ret;

        printf(".");fflush(stdout);
    }

    printf("\nDONE! Closing socket\n");

    ret = socket.close();
    if(ret) {
        printf("socket.close() returned %d\n", ret);
        return 0;
    }
    printf("Closed\n");

    wifi.disconnect();
    return 0;
}
```

OPTIONAL: Create `mbed_app.json`

```
{
    "target_overrides": {
        "*": {
            "platform.stdio-convert-newlines": true,
            "platform.stdio-baud-rate": 115200
        }
    }
}
```

Build&Run.

### Result

Output:
```
Connected to WiFi
Connected!
Receiving 100kB
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
DONE! Closing socket
```

So the test never completes.
Data is coming through without any corruption, but the driver hangs on `close()`.

I verified from the ST's datasheet that this is basically design limitation on the AT command set
http://www.st.com/content/ccc/resource/technical/document/user_manual/4e/4d/c3/82/43/f1/4c/24/DM00100306.pdf/files/DM00100306.pdf/jcr:content/translations/en.DM00100306.pdf

```
2.18 AT+S.SOCKC: close socket
The SOCKC command allows to close socket.
Note: Both for TCP and UDP sockets, flushing pending data (using the AT+S.READ command) is
mandatory before closing the socket connection (AT+S.SOCKC). If the buffer is not erased,
the “ERROR: Pending data” is raised.
```

**Comment by SeppoTakalo** [comment]
CC: @betzw

**Comment by betzw** [comment]
A very first observation, after having read this post only on my cellular phone:
To me it seems as if this test might run into an endless loop in case the server closes the connection before having sent `100000+1` bytes ...
Pls. note, that `socket.recv(buf, 100)` returns zero in case the connection gets closed by the server (and *not* a negative error code).

**Comment by juhaylinen** [comment]
The test seems to get stuck to this loop https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/blob/master/SPWFSAxx.cpp#L713 when socket.close(); is called.

**Comment by betzw** [comment]
Which version/sha-id of the driver are you using?

**Comment by juhaylinen** [comment]
I'm using the latest version v1.1.6 from the wifi-x-nucleo-idw01m1 driver and mbed-os-5.7.7

**Comment by betzw** [comment]
Could you pls. try to run the test again and wait ... even if it might take a very long time, the socket should close prior or later.

**Comment by juhaylinen** [comment]
I run the test few times and you are correct the socket closes eventually but it can take hours.

**Comment by SeppoTakalo** [comment]
I updated the initial message.
I can now confirm that the driver downloads the data correctly but get stuck on the `close()` call.

This is because the AT-command set do not allow to close socket if there is pending data. But with RFC 864, the server keeps sending until the client closes. So it will never stop.

**Comment by betzw** [comment]
I confirm :cry: 

cc @nikapov-ST

**Comment by betzw** [comment]
@SeppoTakalo, how far is this a blocking issue for yourself?

**Comment by betzw** [comment]
Closing the issue.
Pls. feel free to re-open this issue in case of necessity!

**Comment by SeppoTakalo** [comment]
Does not feel right to close without any fix.
Can you add for example "Known issues" or "Known limitations" list into the README.md, similar what the ESP driver has.

**Comment by betzw** [comment]
I have uploaded a new version of the `README.md`. 
Pls. let me know if this is fitting what you suggested.

**Comment by SeppoTakalo** [comment]
Yes. This is correct.
