### ISSUE TITLE
Question: Hardware flow control?

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/wifi-x-nucleo-idw01m1#2]
Hi @betzw,

I was wondering why you have not enabled hardware flow control in the serial driver? I was under the impression that the SPWF01SA supported flow control?

Thank you!

Marcus

**Comment by marcuschangarm** [comment]
So, it goes: 

```
BufferedSerial -> RawSerial -> SerialBase
```

Inside SerialBase, you'll find this command:

```
    /** Set the flow control type on the serial port
     *
     *  @param type the flow control type (Disabled, RTS, CTS, RTSCTS)
     *  @param flow1 the first flow control pin (RTS for RTS or RTSCTS, CTS for CTS)
     *  @param flow2 the second flow control pin (CTS for RTSCTS)
     */
    void set_flow_control(Flow type, PinName flow1=NC, PinName flow2=NC);
```

https://github.com/ARMmbed/mbed-os/blob/master/drivers/SerialBase.h#L154-L162

**Comment by betzw** [comment]
Ciao @marcuschangarm,
thanks a lot for this precious input. Will try to support HW flow control asap!

cc @nikapov-ST, @screamerbg

**Comment by marcuschangarm** [comment]
Awesome! Looking forward to it! 😄

**Comment by betzw** [comment]
I have just added the support for HW flow control.

**Comment by marcuschangarm** [comment]
Wow! That was quick! Thank you! 😄
