### ISSUE TITLE
Status callback is not called upon connection

### ISSUE THREAD

**Issue by michalpasztamobica** [ARMmbed/wifi-x-nucleo-idw01m1#21]
To reproduce the issue you can run the [mbed-os greentea interface tests](https://github.com/ARMmbed/mbed-os/tree/master/TESTS/network/interface) or write a sample program that calls:
1) attach(cb),
2) connect,
3) waits to see the callback called due to successful connect.

I checked that the connections succeeds and the test hangs when waiting for the callback.
Looking briefly into the source code I did not find any obvious error. I did not check if other events are being advertised.

**Comment by avilei** [comment]
As stated on the component page on mbed.com, this component is deprecated and Not Recommended for New Design. If you need to use WiFi with ST hardware, please do use the B-L475E-IOT01A board, which is actively maintained in Mbed.

**Comment by michalpasztamobica** [comment]
@avilei , thanks for pointing this out. I didn't notice the comment in README. 
Closing the issue, removing IDW01M from our CI. I checked that the IOT01A is already there.
