### ISSUE TITLE
Which board is which, more step-by-step info

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/wifi-x-nucleo-idw01m1#4]
On how to 
1) recognize the boards 
2) how to really configure it

**Comment by betzw** [comment]
> On how to
> 1.recognize the boards

The two expansion boards are two different products. You can distinguish them easily as the X-NUCLEO-IDW01M1 comes with a Morho connector only, while the X-NUCLEO-04A1 features an Arduino connector (only).

> 2.how to really configure it

In the `mbed_app.json` file of your application you need to set configuration variable  `idw0xx1.expansion-board` to value `IDW01M1` (default) or `IDW04A1`.
For the X-NUCLEO-IDW04A1 you might also need to define macro `IDW04A1_WIFI_HW_BUG_WA`.

**Comment by JanneKiiskila** [comment]
This repository already HAS the `mbed_lib.json`, does it not get defined via that? 

(I.e. - should I add that same define to the config example in configs/wifi-....json for this module as well?).

**Comment by betzw** [comment]
In `mbed_lib.json` the default value for which expansion board to use gets defined (i.e. `IDW01M1`). 
This can be overridden **if needed** in the application file `mbed_app.json` under the `target_overrides` section with `IDW04A1` (or redundantly set another time to `IDW01M1`).

**Comment by JanneKiiskila** [comment]
Most novices will need an practical example on that.

**Comment by betzw** [comment]
Could you pls. provide me with an ARM-official link to the manual for the mbed config system?

**Comment by JanneKiiskila** [comment]
@adbridge or @0xc0170  - would you know where such document would be available?

**Comment by JanneKiiskila** [comment]
Think I found something here: https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/config_system/

**Comment by JanneKiiskila** [comment]
https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/pull/5
