### ISSUE TITLE
Build failures on ARM compiler 5 and IAR 7

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/wifi-x-nucleo-idw01m1#7]
I spotted from my CI runs that after latest changes, the master of this driver is broken on ARM and IAR

```
22:22:58 Compile [ 99.1%]: SPWFSAxx.cpp
22:22:58 [Warning] SPWFSA01.h@62,0:  #1300-D: _read_in inherits implicit virtual
22:22:58 
[Error] SPWFSAxx.cpp@341,0:  #20: identifier "index" is undefined
```
@betzw Please check.

**Comment by betzw** [comment]
The warning should be easy to solve.
Regarding the compilation error I would like to ask your help:
Unfortunately, I do not have access to ARM a/o IAR, so could you pls. try to re-compile again after substituting in file `SPWFSAxx.cpp` call `index(...)` with a call to `strchr(...)`?

Thanks in advance!

**Comment by SeppoTakalo** [comment]
It should work as `index()` is marked LEGACY in C standards and should be replaced with `strchr()`
http://pubs.opengroup.org/onlinepubs/009695399/functions/index.html

I'll check

**Comment by betzw** [comment]
Thanks and sorry for the inconvenience :flushed:

**Comment by SeppoTakalo** [comment]
Yes, it seems to fix the build at least on ARM. My IAR setup is not in working condition.

So only change required to replace `index()` with `strchr()`
```
        if(_parser.recv("%[^\n]\n", _msg_buffer) && _recv_delim_lf())
        {
            if(strstr(_msg_buffer, ":24:") != NULL) { // WiFi Up
                debug_if(_dbg_on, "AT^ %s\n", _msg_buffer);
                if(strchr(_msg_buffer, '.') != NULL) { // IPv4 address
                    break;
                } else {
                    continue;
                }
```

**Comment by betzw** [comment]
Will come up with a new `master` branch commit asap!

**Comment by betzw** [comment]
Done.

**Comment by SeppoTakalo** [comment]
Fixed.
