### ISSUE TITLE
idw01m1 not initializing correctly with nucleo_f429zi

### ISSUE THREAD

**Issue by JammuKekkonen** [ARMmbed/wifi-x-nucleo-idw01m1#8]
When using idw01m1 with nucleo-429zi, the wifi module is not working after board boot. The situation can be corrected by powering up the board, pressing reset on wifi module and then pressing reset on board.

**Comment by betzw** [comment]
@nikapov-ST pls. have a look.

**Comment by betzw** [comment]
@JammuKekkonen, which pins are you passing to the constructor?

**Comment by betzw** [comment]
@JammuKekkonen, do you still face this issue?

**Comment by betzw** [comment]
@JammuKekkonen, if not applicable anymore, pls. close this issue.

**Comment by betzw** [comment]
I am gonna close this now, pls. re-open and elaborate a bit more on this issue if it still applies.
