### ISSUE TITLE
`bzero()` does not exist in ARM or IAR

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/wifi-x-nucleo-idw01m1#9]
In SPWFSA.h line 88-90
```
    void reset(void) {
        bzero(this, sizeof(*this));
    }
```

Function `bzero()` does not seem to exists in ARM or IAR compiler.
Replace with `memset()`

**Comment by betzw** [comment]
Should be fixed with [this](https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/commit/8c3a3fbbdc3d8e604127f6d06645d93f691a592a) commit.
Pls. let me know if we can close the issue.

**Comment by SeppoTakalo** [comment]
![screen shot 2018-01-09 at 12 03 34](https://user-images.githubusercontent.com/3104794/34715386-26fe2178-f535-11e7-967b-31b30ce1deb2.png)
Test build is fixed now.
